### ISSUE TITLE
How to create PeerAdmin card for multichannel-multipeer network

### ISSUE THREAD

**Issue by kjreddyy** [rshrimp/MortgageBlockchainFabric#1]
Mtrgexchg has three channels and seven peers.  What is the best way to create PeerAdmin card?  Do we need to create one PeerAdmin card or is it necessary to create seven PeerAdmin cards one for each peer. I believe, it is one PeerAdmin card for the Business network.  We couldn't accommodate all three channels in a .connection.json file.  Can anyone suggest a template for multichannel and multi-peer .connection.json file.

**Comment by rshrimp** [comment]
Each org has set number of users created. Please see config tx.yaml. You can use them to connect to a channel provided the peer associated to its org has chaincode access.

**Comment by kjreddyy** [comment]
Thanks for your suggestion.  After going through tx.yaml file, it was realized that mrtgexchg has three channels and 7 orgs.   Each org has one peer i.e. peer0.  Do we need to create a single peeradmin card for mrtgexchg network. We couldn't create a single peeradmin card for three channel and seven Org network.  Could you please help us to create a peeradmin card.
