### ISSUE TITLE
config not working 

### ISSUE THREAD

**Issue by fugazi32** [rshrimp/MortgageBlockchainFabric#2]
While running the createArtificats. sh  
./scripts/createArtifacts.sh: line 7: cryptogen: command not found
\e[5;32;40mgenerating geneis block\e[m 
mkdir: orderer: File exists
./scripts/createArtifacts.sh: line 14: configtxgen: command not found
\e[5;32;40mcreate the channel configuration blocks with this configuration file, by using the other profiles\e[m 
mkdir: channels: File exists
./scripts/createArtifacts.sh: line 19: configtxgen: command not found
./scripts/createArtifacts.sh: line 21: configtxgen: command not found
./scripts/createArtifacts.sh: line 23: configtxgen: command not found
\e[5;32;40mgenerate the anchor peer update transactions\e[m 
./scripts/createArtifacts.sh: line 29: configtxgen: command not found
./scripts/createArtifacts.sh: line 31: configtxgen: command not found
./scripts/createArtifacts.sh: line 33: configtxgen: command not found

**Comment by rshrimp** [comment]
You need to get your path right so that cryptogen is available.  

Please read readme.md. Before you can use this repo, get first network working.

**Comment by fugazi32** [comment]
I was able to run the network from inside fabric sample/first network. All the certificates and channels were up and running. Then i  cloned your repo and tried to run createArtificats and gave me the error. in createArtifacts i have export FABRIC_CFG_PATH=./ 
Do i need to assign the path here  for the cryptogen? And what file should i be referencing to for the path?
